server:
  port: 2323

core:
  stream-interval: 500
  stream-default-density: 0.0
  event-name: periodic-event
parser:
  input-directory: ./in
  event-densities:
    -
      name: GOAL
      density: 1
    -
      name: THROWIN
      density: 0.4
    -
      name: ATTACKPASS
      density: 0.7
    -
      name: DEFANSEPASS
      density: 0.4
    -
      name: CORNER
      density: 0.85
    -
      name: OFFSIDE
      density: 0.55
    -
      name: FAUL
      density: 0.8